name: Windows RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Download Ngrok
        shell: powershell
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
          dir

      - name: Start Tunnel
        shell: powershell
        run: |
          ./ngrok/ngrok.exe tcp 3389
